package banking;


/**
 *
 * @author danie
 */
public class Operations extends javax.swing.JFrame {
    private static BankAccount account;

    /**
     * Creates new form Operations
     */
    
    static CurrentAccount currentAccount;
    static OverdraftAccount overdraftAccount;
    
    
    public Operations(BankAccount account) {
    initComponents();
    this.account = account;
    updateBalanceDisplay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOp = new javax.swing.JPanel();
        amountOpLbl = new javax.swing.JLabel();
        tfAmount = new javax.swing.JTextField();
        withdrawBtn = new javax.swing.JButton();
        depositBtn = new javax.swing.JButton();
        spOperations = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        quitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        amountOpLbl.setText("amount");

        withdrawBtn.setText("Deposit");
        withdrawBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawBtnActionPerformed(evt);
            }
        });

        depositBtn.setText("Withdraw");

        txtArea.setColumns(20);
        txtArea.setRows(5);
        spOperations.setViewportView(txtArea);

        quitBtn.setText("Quit");
        quitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOpLayout = new javax.swing.GroupLayout(panelOp);
        panelOp.setLayout(panelOpLayout);
        panelOpLayout.setHorizontalGroup(
            panelOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpLayout.createSequentialGroup()
                .addGroup(panelOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOpLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panelOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spOperations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panelOpLayout.createSequentialGroup()
                                    .addComponent(withdrawBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(depositBtn))
                                .addGroup(panelOpLayout.createSequentialGroup()
                                    .addComponent(amountOpLbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelOpLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(quitBtn)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        panelOpLayout.setVerticalGroup(
            panelOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountOpLbl)
                    .addComponent(tfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(withdrawBtn)
                    .addComponent(depositBtn))
                .addGap(18, 18, 18)
                .addComponent(spOperations, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(quitBtn)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelOp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelOp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void withdrawBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawBtnActionPerformed
        // TODO add your handling code here:
        // Parse the deposit amount from the text field
    Double depositAmount = Double.valueOf(tfAmount.getText());

    // Perform deposit
    account.deposit(depositAmount);

    // Update UI components, like the balance display
    updateBalanceDisplay();
    }//GEN-LAST:event_withdrawBtnActionPerformed

    private void quitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Account accountFrame = new Account();
        accountFrame.setVisible(true);
    }//GEN-LAST:event_quitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Operations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Operations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Operations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Operations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Operations(account).setVisible(true);
               // new Operations(overdraftAccount).setVisible(true);
            }
        });
    } 
        
        
    
    private void updateBalanceDisplay() {
    // Ensure that 'account' is not null before attempting to call methods on it
    if (account != null) {
        // Assuming the BankAccount class has a getBalance method that returns a double
        double balance = account.getBalance();
        txtArea.setText("Balance: " + String.format("%.2f", balance)); // Format to 2 decimal places
    } else {
        txtArea.setText("Balance: N/A");
    }
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountOpLbl;
    private javax.swing.JButton depositBtn;
    private javax.swing.JPanel panelOp;
    private javax.swing.JButton quitBtn;
    private javax.swing.JScrollPane spOperations;
    private javax.swing.JTextField tfAmount;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JButton withdrawBtn;
    // End of variables declaration//GEN-END:variables
}
